name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: "Release docker image"

    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/kreemer/sandbox
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Info
        shell: bash
        run: |
          echo "::group::Info"
          echo "Registered tags: ${{ steps.docker_meta.outputs.tags }}"
          echo "GitHub REF: $GITHUB_REF"
          echo "Branch Name: ${GITHUB_REF##*/}"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "GitHub Short Sha: $(git rev-parse --short HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::endgroup::"
