name: "Release"

on:
  release:
    types:


jobs:

  release:
    name: "Release docker image"

    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kreemer
          password: ${{ secrets.GHCR_TOKEN }}

    
