name: "Release"

on:
  release:
    types:
      - created

env:
  IMAGE_BASENAME: "ghcr.io/kreemer/sandbox"

jobs:
  build:
    name: "Release docker image"

    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE_BASENAME }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Gather informations1
        shell: bash
        id: info1
        run: |
          echo "::set-output name=commit::${GITHUB_SHA}"


      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          commit: ${{ steps.info1.outputs.commit }}

      - name: Gather informations
        shell: bash
        id: info
        run: |
          ls -lA
          echo "::group::Gather informations"
          echo "Image Tag: sha-${GITHUB_SHA::8}"
          echo "Repository: ${IMAGE_BASENAME}"
          echo "Image to tag: ${IMAGE_BASENAME}:sha-${GITHUB_SHA::7}"
          echo "Tags: ${{ steps.docker_meta.outputs.tags }}"
          echo "::endgroup::"
          echo "::set-output name=image::${IMAGE_BASENAME}:sha-${GITHUB_SHA::7}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kreemer
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Release docker image
        shell: bash
        run: |
          echo "::group::Tagging"
          echo "Getting image ${{ steps.info.outputs.image }}"
          docker pull ${{ steps.info.outputs.image }}
          while IFS= read -r tag; do
            echo "Tagging ${{ steps.info.outputs.image }} as ${IMAGE_BASENAME}${tag}"
            docker tag ${{ steps.info.outputs.image }} ${IMAGE_BASENAME}${tag}
          done <<< "${{ steps.docker_meta.outputs.tags }}"
          echo "::endgroup::"

          echo "Pushing image ${IMAGE_BASENAME} to registry"
          docker image push --all-tags ${IMAGE_BASENAME}
