name: "Release"

on:
  push:
    tags:
      - 'v*'


env:
  IMAGE_BASENAME: "ghcr.io/kreemer/sandbox"

jobs:
  build:
    name: "Release docker image"

    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${IMAGE_BASENAME}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Gather informations
        shell: bash
        id: info
        run: |
          echo "::group::Gather informations"
          echo "Image Tag: sha-${GITHUB_SHA::8}"
          echo "Repository: ${IMAGE_BASENAME}"
          echo "Image to tag: ${IMAGE_BASENAME}:sha-${GITHUB_SHA::8}
          echo "::endgroup::"
          echo "::set-output name=image::${IMAGE_BASENAME}:sha-${GITHUB_SHA::8}"
